### PR TITLE
Small part of my changes (progressive)

### PR DESCRIPTION
**Pull request by GabrielRavier**
I am currently redoing all my changes in small parts to make Flamewing content

### CODE REVIEW

**Comment by Clownacy** [comment]
I'll just repost this here, so everything's in one place:

```
[...]I think I should bring this up: the JmpTo labels are meant to have that space after them. The idea is you can find the actual label by searching '[label]:', and you can find the JmpTo versions by searching '[label] '.
```

**Comment by GabrielRavier** [comment]
Oh okay. I won't re-add them

**Comment by GabrielRavier** [comment]
Note : I still would like for this to be merged, as I didn't remove any space after adresses for now (and won't anyway)

**Comment by Clownacy** [comment]
...Yes you did: JmpTo_EndingSequence.

**Comment by GabrielRavier** [comment]
Huh.
I'll correct that.

**Pull request closed without merging**
