### PR TITLE
ATTENTION GRABBING TITLE !!! Lots of documentation added, some options

### PR DESCRIPTION
**Pull request by GabrielRavier**
I added a few options in the header and commented lots of things

### CODE REVIEW

**Comment by flamewing** [comment]
I, for one, hope that you will consider breaking to those changes into a larger number of smaller commits, with more descriptive commit descriptions ("Add files by upload" is not acceptable), and remove the redundant stuff — there are two commits with over 91000 lines (!) changed which undo each other, which is not OK at all.

Nope, I am not touching this.

**Comment by Techokami** [comment]
I would suggest instead squashing these commits into something more concise and informative. Please see [here](https://gist.github.com/patik/b8a9dc5cd356f9f6f980) to learn how.

**Comment by GabrielRavier** [comment]
"there are two commits with over 91000 lines" I had Onedrive problems and that f***** up the files. Didn't see that before commit. I will try to make it into multiple commits.

**Comment by GabrielRavier** [comment]
Please close this

**Pull request closed without merging**
