### PR TITLE
Separating object code and subroutines from s2.asm

### PR DESCRIPTION
**Pull request by Leo40Git**
### DO NOT MERGE YET - WORK IN PROGRESS

~~Because having a file so big it outright causes Notepad++ to *crash* is kinda dumb.~~

~~ASM files will be organized like the Sonic 1 disassembly: object code and related subroutines go in the "_incObj" folder, while other subroutines will go in the "_inc" folder.~~

The file will be split using the JmpTo blocks as "delimiters" of sorts.

The 3 ASM files in the "misc" folder will be inlined into their object's ASM files (why are they separate, anyway?)

----
**Note:** I have no idea what kind of effect this might have on assembly time. If this is a bad idea, please tell me.

### CODE REVIEW

**Comment by Clownacy** [comment]
Last I checked, it wasn't the filesize itself that causes Notepad++ to crash, but actually its broken syntax highlighting.

Anyway, as I said [here](https://github.com/sonicretro/s2disasm/issues/4#issuecomment-331165783), personally I'd rather the ASM be broken up in a way that matches how the original source code was. Also, I don't think '_inc' and '_incObj' matches the disasm's naming scheme at all.

In case you don't know, a lot of people hate the S1 Git disasm specifically because of the way it was broken up. I've seen way more people complain that S1 was broken up rather than S2 being a single file.

**Comment by Leo40Git** [comment]
...really? Huh. Welp, time to reset, I guess.  
All those wasted Ctrl+C/Ctrl+V presses! /s

Just to clarify, splitting it based on your theory would mean that the JmpTo blocks act as "delimiters" between the files, correct?

**Comment by Clownacy** [comment]
Yeah.

**Comment by Leo40Git** [comment]
```
    if gameRevision<2
	nop
    endif```
These "stray" NOP commands also seem to act as delimiters between source files.

**Comment by Clownacy** [comment]
...I know. I already said that in the post I linked.

**Comment by Leo40Git** [comment]
sorry, i cannot read

**Comment by Leo40Git** [comment]
sorry for dying for a bit

Anyway, some questions before I continue:
- Should the initialization and V/H-int routines be separated from the main file?
- As it stands, the DMA routines, the decompression routines, and the PLC + DPLC routines will be shoved into one file.  
Should this remain, or should they be further split? If split further, here's a rough idea about how it'll go:
  - DMA routines -> source/dma.asm
  - Nemesis, PLC, DPLC -> source/dec/nem.asm
  - Enigma -> source/dec/eni.asm
  - Kosinski -> source/dec/kos.asm

**Comment by Leo40Git** [comment]
I can't think of a good naming scheme that would work for both files containing one object and files containing multiple objects...

**Comment by Leo40Git** [comment]
closed since A) i ended up just cloning S1's way and B) literally no one wants this

**Pull request closed without merging**
