### PR TITLE
Actual commit (part 1)

### PR DESCRIPTION
**Pull request by GabrielRavier**
As suggested, I'm fragmenting my pull request in parts

### CODE REVIEW

**Comment by GabrielRavier** [comment]
Precision. I branched from the original fork and then reverted to s2.asm then added some things back in.

**Comment by GabrielRavier** [comment]
By the way, is there a discord server for Sonic Retro ?

**Comment by GabrielRavier** [comment]
Oops. Closed it by error.

**Comment by GabrielRavier** [comment]
The  request, not the Discord server.

**Comment by MainMemory** [comment]
There is a Discord server, you have to be a member on the forum to get in: http://forums.sonicretro.org/index.php?showtopic=35696
I don't think you'll find much in the way of hacking discussion there though, hackers tend to go on IRC or the SSRG Discord. The Sonic Retro GitHub has an IRC channel at irc.badnik.zone #repo.

**Comment by GabrielRavier** [comment]
And my pull request ? Can I get it merged ? In less than a week ?

**Comment by GabrielRavier** [comment]
And my pull request ?

I feel ignored.
#ForeverAlone

**Comment by Clownacy** [comment]
I'm not the best at Git, so I was hoping someone else would address this, but wouldn't your current pull request cause a bunch of conflicts when people try to update from master? A lot of your changes are pretty extensive, but almost all of them wind up getting reverted, so people would spend ages fixing conflicts for commits that won't do anything anyway.

**Comment by flamewing** [comment]
What Clownacy days, plus you should clean up the history: less merge commits, less generic commit descriptions. I would also prefer several of these changes to be split into multiple commits because they change to much stuff.

**Comment by GabrielRavier** [comment]
I had reverted to the original file and had started to add back what I had done to avoid the problems you are talking about right now. So to be more clear, I'll instead do another thing : fork again from master and do the exact thing I had done. It will be identical but have only 1 commit.

**Comment by Clownacy** [comment]
If it's gonna be the same, then I think I should bring this up: the JmpTo labels are meant to have that space after them. The idea is you can find the actual label by searching '[label]:', and you can find the JmpTo versions by searching '[label] '.

**Pull request closed without merging**
